version: "3.3"

services:
  api:
    container_name: icp-gahara-backend
    image: bintangrezeka/icp-gahara-backend:latest
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./public:/usr/src/app/public/
    depends_on:
      - mariadb-sql
  mariadb-sql:
    container_name: mariadb-sql
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: icpgahara2023
      MARIADB_USER: icpgahara
      MARIADB_PASSWORD: icpgahara2023
    ports:
      - 3306:3306
    volumes:
      - ./data-sql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mariadb-sql
